---
- name: build the project
  delegate_to: localhost
  run_once: true
  ansible.builtin.command: skaffold build --namespace "{{ ns }}" --file-output "{{ build_json_dir }}/{{ project_name }}.json"
  when: build is true
