---
- name: Retrieve NATS certs and creds for local use.
  hosts: localhost
  connection: local
  vars:
    ns: qa
    nats_cmd_pod: nats-box
    local_path: "."
    creds_path: /nsc/nkeys/creds/cyverse/de
    creds_file: services.creds
    client_tls_path: /etc/nats/tls/nats
    client_tls_remote_cert_file: tls.crt
    client_tls_local_cert_file: nats-client-tls.crt
    client_tls_remote_key_file: tls.key
    client_tls_local_key_file: nats-client-tls.key
    server_tls_path: /etc/nats/tls/cluster
    server_tls_remote_cert_file: tls.crt
    server_tls_local_cert_file: nats-server-tls.crt
    server_tls_remote_key_file: tls.key
    server_tls_local_key_file: nats-server-tls.key
    ca_tls_path: /etc/nats/tls/ca
    ca_tls_remote_cert_file: ca.crt
    ca_tls_local_cert_file: nats-ca.crt
    ca_tls_remote_key_file: tls.key
    ca_tls_local_key_file: nats-ca-tls.key

  tasks:
    - name: get the name of the nats-box pod
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ ns }}"
        label_selectors:
          - app.kubernetes.io/name=nats
          - app.kubernetes.io/instance=nats
          - app.kubernetes.io/component=nats-box
      register: nats_box_pod

    - name: get the name of the nat-0 pod
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ ns }}"
        label_selectors:
          - app.kubernetes.io/name=nats
          - app.kubernetes.io/instance=nats
          - app.kubernetes.io/component=nats
          - statefulset.kubernetes.io/pod-name=nats-0
      register: nat_0_pod

    - name: get the services.creds file from the nats-box pod
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        pod: "{{ nats_box_pod.resources[0].metadata.name }}"
        remote_path: "{{ creds_path }}/{{ creds_file }}"
        local_path: "{{ local_path}}/services.creds"
        namespace: "{{ ns }}"
        state: from_pod

    - name: get the nats client tls cert
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        container: nats
        pod: "{{ nat_0_pod.resources[0].metadata.name }}"
        remote_path: "{{ client_tls_path }}/{{ client_tls_remote_cert_file }}"
        local_path: "{{ local_path }}/{{ client_tls_local_cert_file }}"
        namespace: "{{ ns }}"
        state: from_pod

    - name: get the nats client tls key
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        container: nats
        pod: "{{ nat_0_pod.resources[0].metadata.name }}"
        remote_path: "{{ client_tls_path }}/{{ client_tls_remote_key_file }}"
        local_path: "{{ local_path }}/{{ client_tls_local_key_file }}"
        namespace: "{{ ns }}"
        state: from_pod

    - name: get the nats server tls cert
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        container: nats
        pod: "{{ nat_0_pod.resources[0].metadata.name }}"
        remote_path: "{{ server_tls_path }}/{{ server_tls_remote_cert_file }}"
        local_path: "{{ local_path }}/{{ server_tls_local_cert_file }}"
        namespace: "{{ ns }}"
        state: from_pod

    - name: get the nats server tls key
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        container: nats
        pod: "{{ nat_0_pod.resources[0].metadata.name }}"
        remote_path: "{{ server_tls_path }}/{{ server_tls_remote_key_file }}"
        local_path: "{{ local_path }}/{{ server_tls_local_key_file }}"
        namespace: "{{ ns }}"
        state: from_pod

    - name: get the nats ca tls cert
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        container: nats
        pod: "{{ nat_0_pod.resources[0].metadata.name }}"
        remote_path: "{{ ca_tls_path }}/{{ ca_tls_remote_cert_file }}"
        local_path: "{{ local_path }}/{{ ca_tls_local_cert_file }}"
        namespace: "{{ ns }}"
        state: from_pod

    - name: get the nats ca tls key
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s_cp:
        container: nats
        pod: "{{ nat_0_pod.resources[0].metadata.name }}"
        remote_path: "{{ ca_tls_path }}/{{ ca_tls_remote_key_file }}"
        local_path: "{{ local_path }}/{{ ca_tls_local_key_file }}"
        namespace: "{{ ns }}"
        state: from_pod
