---
- name: Add nats helm support
  hosts: localhost
  connection: local
  vars:
    k8s_resc_co_dir: ./k8s-resources
    k8s_resc_sub_dir: resources/addons
    ns: nats
    nats_cmd_pod: nats-box
  tasks:
    - name: Add nats helm repository
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.helm_repository:
        name: nats
        repo_url: https://nats-io.github.io/k8s/helm/charts/
        state: present

    - name: set resc_dir
      set_fact:
        resc_dir: "{{ k8s_resc_co_dir }}/{{ k8s_resc_sub_dir }}"

    - name: Create nats namespace
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.k8s:
        name: "{{ ns }}"
        state: present
        kind: namespace
        api_version: v1

    - name: Install nats helm chart
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
      kubernetes.core.helm:
        name: nats
        chart_ref: nats/nats
        release_namespace: "{{ ns }}"
        wait: true
        values_files:
          - "{{ resc_dir }}/nats/values.yaml"

    - name: run the nsc-init.sh bash script with the namespace as an argument
      ansible.builtin.command: "bash files/nsc-init.sh {{ ns }}"
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
