---
- name: Add nats helm support
  hosts: localhost
  connection: local
  vars:
    k8s_resc_git_repo: changeme
    k8s_resc_git_version: main
    k8s_resc_co_dir: deployment
    k8s_resc_git_dir: k8s-resources
    ns: nats
    nats_cmd_pod: nats-box
  tasks:
    - name: Add nats helm repository
      kubernetes.core.helm_repository:
        name: nats
        repo_url: https://nats-io.github.io/k8s/helm/charts/
        state: present

    - name: Create the staging directory
      ansible.builtin.tempfile:
        state: directory
        suffix: "-nats"
      register: staging_dir

    - name: Clone the repo containing resources
      ansible.builtin.git:
        repo: "{{ k8s_resc_git_repo }}"
        dest: "{{ staging_dir.path }}/{{ k8s_resc_co_dir }}"
        version: "{{ k8s_resc_git_version }}"

    - name: set resc_dir
      set_fact:
        resc_dir: "{{ staging_dir.path }}/{{ k8s_resc_co_dir }}/{{ k8s_resc_git_dir }}"

    - name: Install nats helm chart
      kubernetes.core.helm:
        name: nats
        chart_ref: nats/nats
        release_namespace: "{{ ns }}"
        values_files:
          - "{{ resc_dir }}/resources/nats/values.yml"

    - name: run the nsc-init.sh bash script with the namespace as an argument
      ansible.builtin.command: "bash files/nsc-init.sh {{ ns }}"
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
