---
- name: set up the apt repository
  block:
    - name: get the gpg key
      ansible.builtin.get_url:
        url: https://download.gocd.org/GOCD-GPG-KEY.asc
        dest: /usr/share/keyrings/GOCD-GPG-KEY.asc
        mode: "0644"
        force: true

    - name: de-armor the gpg key
      command: gpg -o /etc/apt/keyrings/gocd.gpg --dearmor /usr/share/keyrings/GOCD-GPG-KEY.asc
      args:
        creates: /etc/apt/keyrings/gocd.gpg

    - name: add the repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/gocd.gpg] https://download.gocd.org /"
        state: present
        update_cache: true

- name: install the go-server package
  ansible.builtin.package:
    name: go-server
    state: present

- name: start and enable go-server
  ansible.builtin.service:
    name: go-server
    state: started
    enabled: true

- name: open port 8153
  community.general.ufw:
    rule: allow
    direction: in
    port: "8153"
    proto: tcp
    src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups['de_haproxy'] }}"
