---
- name: install on ubuntu/deb
  ansible.builtin.include_tasks:
    file: debian_install.yml
  when: ansible_os_family == 'Debian'

- name: install on Red Hat systems
  block:
    - ansible.builtin.include_tasks:
        file: redhat_install.yml

    - ansible.builtin.include_role:
        name: gocd_agent
        tasks_from: redhat_tools.yml
  when: ansible_os_family == 'RedHat'

