---
- name: add the repository
  ansible.builtin.get_url:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd.repo

- name: install go-server
  ansible.builtin.dnf:
    name: go-server
    state: present
    disable_gpg_check: true

- name: start and enable go-server
  ansible.builtin.service:
    name: go-server
    state: started
    enabled: true

- name: open port 8153
  ansible.posix.firewalld:
    state: enabled
    permanent: true
    zone: public
    port: "8153/tcp"
  notify: reload firewalld
