---

- name: add the repository
  ansible.builtin.get_url:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd.repo

- name: install the go-server package
  ansible.builtin.package:
    name: go-server
    state: present

- name: start and enable go-server
  ansible.builin.service:
    name: go-server
    state: started
    enabled: true

- name: open port 8153
  ansible.posix.firewalld:
    port: "8153/tcp"
    state: enabled
    permanent: true
    immediate: true
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups['de_proxy'] }}"
