---
- name: build the release URL
  ansible.builtin.set_fact:
    release_url: "https://github.com/cyverse-de/network-pruner/releases/download/{{network_pruner_version}}"

- name: download the binary
  ansible.builtin.get_url:
    url: "{{release_url}}/network-pruner"
    dest: "/usr/local/bin/network-pruner"
    owner: "root"
    group: "root"
    mode: 0755
    force: true

- name: download the systemd unit file
  ansible.builtin.get_url:
    url: "{{release_url}}/network-pruner.service"
    dest: "/lib/systemd/system/network-pruner.service"
    owner: "root"
    group: "root"
    mode: 0644
    force: true

- name: start the service
  ansible.builtin.systemd_service:
    name: "network-pruner"
    daemon_reload: true
    enabled: true
    state: "restarted"
