apiVersion: v1
kind: Service
metadata:
  name: keycloak
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:123456789012:certificate/00000000-1111-2222-3333-444444444444
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
