apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
  - protocol: TCP
    name: https
    port: 443
    targetPort: http
  selector:
    app: keycloak
  type: LoadBalancer
