---
ansible_python_interpreter: /usr/bin/python3
encoding: UTF8
lc_collate: en_US.UTF-8
lc_ctype: en_US.UTF-8
template: template0
pg_db: postgres
pg_listen_port: 5432
pg_login_user: postgres
pg_login_host: localhost
pg_login_password: Chang3m3
