---
- name: set up the apt repository
  block:
    - name: get the gpg key
      ansible.builtin.get_url:
        url: https://download.gocd.org/GOCD-GPG-KEY.asc
        dest: /usr/share/keyrings/GOCD-GPG-KEY.asc
        mode: '0644'
        force: true

    - name: de-armor the gpg key
      command: gpg -o /etc/apt/keyrings/gocd.gpg --dearmor /usr/share/keyrings/GOCD-GPG-KEY.asc 
      args:
        creates: /etc/apt/keyrings/gocd.gpg

    - name: add the repo 
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/gocd.gpg] https://download.gocd.org /"
        state: present
        update_cache: true

- name: install the go-agent package
  ansible.builtin.package:
    name: go-agent
    state: present

- name: start and enable go-agent
  ansible.builtin.service:
    name: go-agent
    state: started
    enabled: true


