---
- name: setup gocd worker on debian systems
  block:
    - name: install gocd worker
      ansible.builtin.include_tasks:
        file: debian_install.yml
    - name: install tools
      ansible.builtin.include_tasks:
        file: debian_tools.yml
  when: ansible_os_family == 'Debian'

- name: setup gocd worker on Red Hat systems
  block:
    - name: install gocd worker
      ansible.builtin.include_tasks:
        file: redhat_install.yml
    - name: install tools
      ansible.builtin.include_tasks:
        file: redhat_tools.yml
  when: ansible_os_family == 'RedHat'

- name: set the server url
  ansible.builtin.lineinfile:
    path: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
    regexp: '^wrapper\.app\.parameter\.101'
    line: "wrapper.app.parameter.101=https://{{ gocd_external_domain }}/go"
  notify:
    - restart go-agent
