---
- name: install git
  ansible.builtin.package:
    name: git
    state: present

- name: add the kubernetes yum repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes YUM repository
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

- name: install kubectl
  ansible.builtin.package:
    name: kubectl 
    state: present

- name: install skaffold
  ansible.builtin.get_url:
    url: "{{gocd_skaffold_url}}"
    dest: /usr/local/bin/skaffold
    mode: "a+x"

- name: install epel-release
  ansible.builtin.package:
    name: epel-release
    state: present

- name: install ansible
  ansible.builtin.package:
    name: ansible
    state: present

- name: install python3-pip
  ansible.builtin.package:
    name: python3-pip

- name: install libpq-devel
  ansible.builtin.package:
    name: libpq-devel

# - name: install python-devel
#   ansible.builtin.package:
#     name: python-devel

- name: install psycopg2
  ansible.builtin.package:
    name: python-psycopg2

- name: install kubernetes lib
  ansible.builtin.package:
    name: python-kubernetes

- name: install unzip
  ansible.builtin.package:
    name: unzip

- name: install tar
  ansible.builtin.package:
    name: tar

- name: check for migrate command
  command: which migrate
  changed_when: false
  register: migrate_installed
  failed_when: migrate_installed.rc not in [0, 1]

- name: init db | extract migrate tarball
  ansible.builtin.unarchive:
    src: "https://github.com/golang-migrate/migrate/releases/download/{{ migrate_release_version }}/{{ migrate_tarball_name }}"
    dest: "/usr/local/bin/"
    remote_src: yes
    creates: "/usr/local/bin/migrate"
  when: migrate_installed.rc == 1

- name: init db | install migrate
  ansible.builtin.file:
    path: "/usr/local/bin/migrate"
    mode: '0755'
    state: file
