---
- name: install condor when centos
  block:
  - name: import the PGP key used by HTCondor
    ansible.builtin.rpm_key:
      key: "https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key"
      state: "present"

  - name: add the YUM repository file
    ansible.builtin.yum:
      name: "https://research.cs.wisc.edu/htcondor/repo/current/htcondor-release-current.el8.noarch.rpm"
      state: "present"

  - name: install Condor
    ansible.builtin.yum:
      name: "condor-all"
      state: "present"
      enablerepo: "powertools"
  when: ansible_facts['distribution'] == 'CentOS'

- name: install condor when ubuntu
  block:
  - name: get the apt key
    ansible.builtin.get_url:
      url: https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key
      dest: /etc/apt/keyrings/HTCondor-10.x-Key

  - name: copy /etc/apt/sources.list.d/htcondor.sources
    ansible.builtin.template:
      src: htcondor.sources.j2
      dest: /etc/apt/sources.list.d/htcondor.sources

  - name: install htcondor
    ansible.builtin.apt:
      pkg:
      - htcondor
      state: present
      update_cache: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true

- name: enable username sharing
  ansible.builtin.template:
    dest: "/etc/condor/config.d/20-job-user.config"
    src: "20-job-user.config"

- name: configure the pool password if there is one
  block:
  - name: store the pool password
    ansible.builtin.command: "condor_store_cred -f /var/lib/condor/pool_password -p {{ condor_pool_password | quote }}"

  - name: configure the pool password location
    ansible.builtin.copy:
      dest: "/etc/condor/config.d/20-pool-password.config"
      src: "20-pool-password.config"
  when: condor_pool_password != ""
