- name: ensure that tzdata is installed via package manager
  become: true
  package:
    name: 
      - tzdata
    state: latest
# tzdata-java hasn't been available in ubuntu since 16.04 https://askubuntu.com/questions/795901/what-happened-to-tzdata-java-in-xenial-16-04

- name: link the correct time zone to /etc/localtime
  become: true
  file:
    path: /etc/localtime
    state: link
    src: "/usr/share/zoneinfo/{{ timezone }}"
    force: true
    mode: 0644

- name: set current time zone in /etc/timezone
  become: true
  template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644