---
_dbms_postgresql_version: "{{ dbms_postgresql_version | default(14) }}"

_dbms_reboot_allowed: "{{ dbms_reboot_allowed | d(false) }}"

_dbms_checkpoint_completion_target: >-
  {{ dbms_checkpoint_completion_target | d(0.9) }}
_dbms_checkpoint_timeout: "{{ dbms_checkpoint_timeout | default(15) }}"
_dbms_effective_io_concurrency: "{{ dbms_effective_io_concurrency | d(200) }}"

_dbms_log_line_prefix: "{{ dbms_log_line_prefix | default('< %m %r >') }}"
_dbms_log_min_duration: "{{ dbms_log_min_duration | default(1000) }}"

_dbms_maintenance_work_mem: "{{ dbms_maintenance_work_mem | default(2) }}"

_dbms_max_connections: "{{ dbms_max_connections | default(500) }}"

_dbms_port: "{{ dbms_port | default(5432) }}"

_dbms_effective_cache_size: "{{ dbms_effective_cache_size | default(None) }}"
_dbms_random_page_cost: "{{ dmbs_random_page_cost | default(1.1) }}"

_dbms_replication_password: "{{ dbms_replication_password | default(None) }}"
_dbms_replication_start: "{{ dbms_replication_start | default(false) }}"
_dbms_replication_user: "{{ dbms_replication_user | default('postgres') }}"

_dbms_wal_keep_segments: "{{ dbms_wal_keep_segments | default(4000) }}"
_dbms_max_wal_senders: "{{ dbms_max_wal_senders | default(120) }}"
_dbms_max_wal_size: "{{ dbms_max_wal_size | default(8) }}"
_dbms_min_wal_size: "{{ dbms_min_wal_size | default(2) }}"

_dbms_work_mem: "{{ dbms_work_mem | default(32) }}"

_dbms_mem_num_huge_pages: "{{ dbms_mem_num_huge_pages | default(60000) }}"

_dbms_max_worker_processes: "{{ dbms_max_worker_processes | default(None) }}"
_dbms_max_parallel_maintenance_workers: >-
  {{ dbms_max_parallel_maintenance_workers | d(2) }}
_dbms_max_parallel_workers_per_gather: >-
  {{ dbms_max_parallel_workers_per_gather | d(2) }}

_dbms_connection_user: "{{ dbms_connection_user | default('de') }}"
_dbms_connection_pass: "{{ dbms_connection_pass | default('Ch@ng3M3') }}"

_grouper_connection_user: "{{ grouper_connection_user | default('grouper') }}"
_grouper_connection_pass: "{{ grouper_connection_pass | default('Ch@ng3m3') }}"

dbms_allowed_local_addresses:
  - "127.0.0.1/32"
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"

dbms_allowed_remote_addresses: []

ansible_python_interpreter: /usr/bin/python3
encoding: UTF8
lc_collate: en_US.UTF-8
lc_ctype: en_US.UTF-8
template: template0
de_db_version: master
de_db_migration_cmd: force 18
notifications_db_version: main
metadata_db_version: master
mgmt_version: main
pg_db: postgres
pg_listen_port: 5432
pg_login_user: postgres
pg_login_host: localhost
pg_login_password: Chang3m3
cleanup: true
migrate: true
create_user: true
create_dbs: true
unleash: true
grouper: true
qms: true
install_exts: true
migrate_release_version: v4.17.0
migrate_tarball_name: migrate.linux-amd64.tar.gz # or migrate.darwin-amd64.tar.gz
install_dir: /usr/local/bin # no trailing slash
