---
- name: enable the worker role
  become: true
  ansible.builtin.template:
    dest: "/etc/condor/config.d/01-execute.config"
    src: "01-execute.config.j2"

- name: enable partitionable slots
  become: true
  ansible.builtin.copy:
    dest: "/etc/condor/config.d/02-partitionable-slots.config"
    src: "02-partitionable-slots.config"

- name: indicate that the node is capable of running road-runner
  become: true
  ansible.builtin.copy:
    dest: "/etc/condor/config.d/20-road-runner.config"
    src: "20-road-runner.config"
