---
- name: build the release URL
  ansible.builtin.set_fact:
    release_url: "https://github.com/cyverse-de/image-janitor/releases/download/{{image_janitor_version}}"

- name: create /opt/image-janitor directory
  ansible.builtin.file:
    path: "/opt/image-janitor"
    state: "directory"
    owner: "condor"
    group: "condor"
    mode: 0775

- name: create the excludes file
  ansible.builtin.template:
    src: "excludes.j2"
    dest: "/opt/image-janitor/excludes"

- name: download the binary
  ansible.builtin.get_url:
    url: "{{release_url}}/image-janitor"
    dest: "/usr/local/bin/image-janitor"
    owner: "root"
    group: "root"
    mode: 0755
    force: true

- name: download the systemd unit file
  ansible.builtin.get_url:
    url: "{{release_url}}/image-janitor.service"
    dest: "/lib/systemd/system/image-janitor.service"
    owner: "root"
    group: "root"
    mode: 0644
    force: true

- name: start the service
  ansible.builtin.systemd_service:
    name: "image-janitor"
    daemon_reload: true
    enabled: true
    state: "restarted"
