---
- name: concourse | set the concourse dir
  ansible.builtin.set_fact:
    concourse_dir: "{{ (concourse_install_dir, 'concourse') | path_join }}"

- name: concourse | set the web environment file
  ansible.builtin.set_fact:
    concourse_env_file: "{{ (concourse_dir, 'env.conf') | path_join }}"

- name: concourse | set the TLS private key path
  ansible.builtin.set_fact:
    concourse_private_key: "{{ (concourse_dir, 'concourse.key') | path_join }}"

- name: concourse | create the TLS private key
  become: true
  community.crypto.openssl_privatekey:
    path: "{{ concourse_private_key }}"

- name: concourse | create the CSR signing request
  become: true
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ concourse_private_key }}"
    common_name: "{{ concourse_external_url }}"
    organization_name: CyVerse Discovery Environment
  register: csr

- name: concourse | create the self-signed certificate from CSR
  become: true
  community.crypto.x509_certificate:
    path: "{{ (concourse_dir, 'concourse.crt') | path_join }}"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ concourse_private_key }}"
    provider: selfsigned

- name: concourse | open the 8080 port
  become: true
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: concourse | open the 8383 port
  become: true
  community.general.ufw:
    rule: allow
    port: '8383'
    proto: tcp

- name: concourse | open the 2222 port
  become: true
  community.general.ufw:
    rule: allow
    port: '2222'
    proto: tcp

- name: concourse | install web environment file
  become: true
  ansible.builtin.copy:
    dest: "{{ concourse_env_file }}"
    mode: '0644'
    content: |
      CONCOURSE_EXTERNAL_URL={{concourse_external_url}}
      CONCOURSE_TLS_CERT={{ (concourse_dir, 'concourse.crt') | path_join }}
      CONCOURSE_TLS_KEY={{ concourse_private_key }}
      CONCOURSE_TLS_BIND_PORT=8383
      CONCOURSE_ADD_LOCAL_USER={{concourse_login_user}}:{{concourse_login_password}}
      CONCOURSE_MAIN_TEAM_LOCAL_USER={{concourse_login_user}}
      CONCOURSE_SESSION_SIGNING_KEY={{(concourse_dir, 'session_signing.key') | path_join}}
      CONCOURSE_TSA_HOST_KEY={{(concourse_dir, 'tsa_host.key') | path_join}}
      CONCOURSE_TSA_AUTHORIZED_KEYS={{(concourse_dir, 'authorized_worker_keys') | path_join}}
      CONCOURSE_POSTGRES_HOST={{groups['dbms_primary'][0]}}
      CONCOURSE_POSTGRES_PORT={{pg_listen_port}}
      CONCOURSE_POSTGRES_DATABASE={{concourse_db}}
      CONCOURSE_POSTGRES_USER={{concourse_database_user}}
      CONCOURSE_POSTGRES_PASSWORD={{concourse_database_pass}}
  notify: 
    - systemctl daemon-reload
    - restart concourse-web

- name: concourse | install web systemd service file
  become: true
  ansible.builtin.copy:
    dest: "/etc/systemd/system/concourse-web.service"
    mode: '0644'
    content: |
      [Unit]
      Description=Concourse Web Service
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=1
      User={{concourse_user}}
      EnvironmentFile={{(concourse_dir, 'env.conf') | path_join}}
      ExecStart={{(concourse_install_dir, 'concourse/bin/concourse') | path_join}} web --encryption-key {{concourse_encryption_key}}

      [Install]
      WantedBy=multi-user.target
  notify: 
    - systemctl daemon-reload
    - restart concourse-web

