# -*- mode: yaml -*-

version: '2'
networks:
  default:
    external:
      name: de-${DE_ENV}
services:
  ###
  # Set up the configuration containers
  ###
  config_image_janitor:
    image: gims.cyverse.org:5000/de-configs-${DE_ENV}:${DE_TAG}
    labels:
      org.cyverse.name: "image-janitor"
      org.cyverse.type: "configs"

  ###
  # Service and UI definitions
  ###
  image_janitor:
    image: discoenv/image-janitor:${DE_TAG}
    command: --config /etc/iplant/de/jobservices.yml
    environment:
      - DE_ENV=${DE_ENV}
      - SERVICE_TAGS=${DE_TAG}
    restart: unless-stopped
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    volumes_from:
      - config_image_janitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/image-janitor:/opt/image-janitor
    labels:
      org.cyverse.name: "image-janitor"
      org.cyverse.type: "service"
