---
- name: Initialize databases
  hosts: dbms
  vars:
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  tasks:
    - name: init db | create connection user-
      community.postgresql.postgresql_user:
        db: "{{ pg_db }}"
        port: "{{ pg_listen_port }}"
        name: "{{ _dbms_connection_user }}"
        password: "{{ _dbms_connection_pass }}"

    - name: init db  | create de database
      community.postgresql.postgresql_db:
        name: "de"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"

    - name: init db  | create notifications database
      community.postgresql.postgresql_db:
        name: "notifications"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"

    - name: init db  | create permissions database
      community.postgresql.postgresql_db:
        name: "permissions"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"

    - name: init db  | create metadata database
      community.postgresql.postgresql_db:
        name: "metadata"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"

    - name: init db  | create grouper database
      community.postgresql.postgresql_db:
        name: "grouper"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"

    - name: init db  | create qms database
      community.postgresql.postgresql_db:
        name: "qms"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"

    - name: init db  | create unleash database
      community.postgresql.postgresql_db:
        name: "unleash"
        port: "{{ pg_listen_port }}"
        owner: "{{ _dbms_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"
