---
- name: check if haproxy is installed manually
  ansible.builtin.stat:
    path: /usr/local/sbin/haproxy
  register: h

- name: debug | haproxy_installed
  ansible.builtin.debug:
    var: h

- name: Open the HTTPS Port
  become: true
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Open the API Port
  become: true
  community.general.ufw:
    rule: allow
    port: 5443
    proto: tcp

- name: install | install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present
  when: h.stat is not defined or not h.stat.exists

- name: configure | download dhparam
  ansible.builtin.get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/ssl/dhparam
    owner: root
    group: root
    mode: "0644"

- name: configure | template config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart haproxy
