---
# Users and groups
- block:
  - name: Add the docker group
    group:
       name: docker
       state: present

  - name: Add the docker user
    user:
       name: docker
       shell: /bin/bash
       groups: docker
       append: yes

  - when: "'condor' in group_names"
    name: Add the condor user to the docker group
    user:
       name: condor
       groups: docker
       append: yes
  tags:
      - config
      - config_user

# Install repos and packages
- block:
  - name: Add repo file
    get_url:
      dest: "/etc/yum.repos.d/docker-ce.repo"
      url: "https://download.docker.com/linux/centos/docker-ce.repo"
      mode: 0644
    tags:
        - install

  - name: Install Docker CLI
    package:
      name: docker-ce-cli
      state: present

  - name: Install Docker
    package:
      name: docker-ce
      state: present

  - name: Install containerd.io
    package:
      name: containerd.io
      state: present

  - name: Install docker-compose plugin
    package:
      name: docker-compose-plugin
      state: present
  tags:
      - install

- name: enable docker
  service:
     name: docker
     enabled: yes
  tags:
      - enable_docker

- name: restart docker
  service:
     name: docker
     state: restarted
     enabled: yes
  tags:
      - restart_docker
