---
ns: qa
nats_cmd_pod: nats-box

ui_wildcard_fqdn: "*.cyverse.org"
vice_wildcard_fqdn: "*.cyverse.run"
vice_base_domain: cyverse.run

ca_duration: 8766h # 1 year
ca_renew_before: 240h # 10 days

nats_server_cert_duration: 8766h # 1 year
nats_server_cert_renew_before: 240h # 10 days
nats_client_cert_duration: 8766h # 1 year
nats_client_cert_renew_before: 240h # 10 days

_dbms_postgresql_version: "{{ dbms_postgresql_version | default(14) }}"
_dbms_reboot_allowed: "{{ dbms_reboot_allowed | d(false) }}"
_dbms_checkpoint_completion_target: >-
  {{ dbms_checkpoint_completion_target | d(0.9) }}
_dbms_checkpoint_timeout: "{{ dbms_checkpoint_timeout | default(15) }}"
_dbms_effective_io_concurrency: "{{ dbms_effective_io_concurrency | d(200) }}"
_dbms_log_line_prefix: "{{ dbms_log_line_prefix | default('< %m %r >') }}"
_dbms_log_min_duration: "{{ dbms_log_min_duration | default(1000) }}"
_dbms_maintenance_work_mem: "{{ dbms_maintenance_work_mem | default(2) }}"
_dbms_max_connections: "{{ dbms_max_connections | default(500) }}"
_dbms_port: "{{ dbms_port | default(5432) }}"
_dbms_effective_cache_size: "{{ dbms_effective_cache_size | default(None) }}"
_dbms_random_page_cost: "{{ dmbs_random_page_cost | default(1.1) }}"
_dbms_replication_password: "{{ dbms_replication_password | default(None) }}"
_dbms_replication_start: "{{ dbms_replication_start | default(false) }}"
_dbms_replication_user: "{{ dbms_replication_user | default('postgres') }}"
_dbms_wal_keep_segments: "{{ dbms_wal_keep_segments | default(4000) }}"
_dbms_max_wal_senders: "{{ dbms_max_wal_senders | default(120) }}"
_dbms_max_wal_size: "{{ dbms_max_wal_size | default(8) }}"
_dbms_min_wal_size: "{{ dbms_min_wal_size | default(2) }}"
_dbms_work_mem: "{{ dbms_work_mem | default(32) }}"
_dbms_mem_num_huge_pages: "{{ dbms_mem_num_huge_pages | default(60000) }}"
_dbms_max_worker_processes: "{{ dbms_max_worker_processes | default(None) }}"
_dbms_max_parallel_maintenance_workers: >-
  {{ dbms_max_parallel_maintenance_workers | d(2) }}
_dbms_max_parallel_workers_per_gather: >-
  {{ dbms_max_parallel_workers_per_gather | d(2) }}
