---
- name: pull road-runner image
  shell: docker pull discoenv/road-runner:{{docker.tag}}

- name: dev_check
  set_fact:
    temp_tag

# TODO: come up with a way to generate the file and place it on the remote host
- name: ensure that jobservices.yml exists
  become: yes
  file:
    path: /etc/jobservices.yml
    state: touch

- name: install road-runner
  shell: docker run --rm -v /usr/local/bin:/road-runner --entrypoint "cp" discoenv/road-runner:{{docker.tag}} /go/bin/road-runner /road-runner/road-runner
