---
- name: pull interapps-runner image
  shell: docker pull discoenv/interapps-runner:{{docker.tag}}

- name: dev_check
  set_fact:
    temp_tag

- name: clone k8s-resources locally
  become: no
  local_action:
    module: git
    repo: ssh://git@gitlab.cyverse.org/core-sw/k8s-resources
    dest: k8s-resources
    version: "{{ {'dev' : 'master', 'uat' : 'beta', 'latest' : 'prod'}[docker.tag] | default(docker.tag) }}"
    accept_hostkey: yes
  run_once: True

- name: copy jobservice.yml to the remote host
  copy:
    src: k8s-resources/resources/configs/{{environment_name}}/jobservices.yml
    dest: /etc/jobservices.yml
    mode: 0644

- name: remove local k8s-resources clone
  become: no
  local_action:
    module: file
    state: absent
    path: k8s-resources
  run_once: True

- name: install interapps-runner
  shell: docker run --rm -v /usr/local/bin:/interapps-runner --entrypoint "cp" discoenv/interapps-runner:{{docker.tag}} /go/bin/interapps-runner /interapps-runner/interapps-runner
