---
- name: Initialize the Kubernetes Cluster
  hosts: k8s_controllers
  become: true
  tasks:
  - ansible.builtin.stat:
      path: /etc/kubernetes/admin.conf
    when: inventory_hostname == ansible_play_hosts[0]
    register: admin_conf

  - ansible.builtin.command:
      argv:
      - "kubeadm"
      - "init"
      - "--control-plane-endpoint"
      - "{{ groups['k8s_api_proxy'][0] }}:5443"
      - "--cri-socket"
      - "unix:///var/run/cri-dockerd.sock"
      - "--upload-certs"
      - "--node-name"
      - "{{ inventory_hostname }}"
    when: inventory_hostname == ansible_play_hosts[0]
    register: kubeadm_init_output

  - ansible.builtin.set_fact:
      kubeadm_token: "{{ kubeadm_init_output['stdout'] | regex_search('--token (\\S+)', '\\1') | first }}"
      kubeadm_discovery_hash: "{{ kubeadm_init_output['stdout'] | regex_search('--discovery-token-ca-cert-hash (\\S+)', '\\1') | first }}"
      kubeadm_certificate_key: "{{ kubeadm_init_output['stdout'] | regex_search('--certificate-key (\\S+)', '\\1') | first }}"
    when: inventory_hostname == ansible_play_hosts[0]

- name: Add the Remaining Control Nodes
  hosts: k8s_controllers
  become: true
  tasks:
  - ansible.builtin.command:
      argv:
      - "kubeadm"
      - "join"
      - "{{ groups['k8s_api_proxy'][0] }}:5443"
      - "--cri-socket"
      - "unix:///var/run/cri-dockerd.sock"
      - "--token"
      - "{{ hostvars[groups['k8s_controllers'][0]]['kubeadm_token'] }}"
      - "--discovery-token-ca-cert-hash"
      - "{{ hostvars[groups['k8s_controllers'][0]]['kubeadm_discovery_hash'] }}"
      - "--control-plane"
      - "--certificate-key"
      - "{{ hostvars[groups['k8s_controllers'][0]]['kubeadm_certificate_key'] }}"
      - "--node-name"
      - "{{ inventory_hostname }}"
    when: inventory_hostname != ansible_play_hosts[0]

- name: Add the Worker Nodes
  hosts: k8s_workers
  become: true
  tasks:
  - ansible.builtin.command:
      argv:
      - "kubeadm"
      - "join"
      - "{{ groups['k8s_api_proxy'][0] }}:5443"
      - "--cri-socket"
      - "unix:///var/run/cri-dockerd.sock"
      - "--token"
      - "{{ hostvars[groups['k8s_controllers'][0]]['kubeadm_token'] }}"
      - "--discovery-token-ca-cert-hash"
      - "{{ hostvars[groups['k8s_controllers'][0]]['kubeadm_discovery_hash'] }}"
      - "--node-name"
      - "{{ inventory_hostname }}"

- name: Label the DE Service Nodes
  hosts: k8s_de_workers
  become: true
  tasks:
  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "label"
      - "node"
      - "{{ inventory_hostname }}"
      - "vice=false"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "label"
      - "node"
      - "{{ inventory_hostname }}"
      - "gpu=false"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

- name: Taint and Label the VICE Worker Nodes
  hosts: k8s_vice_workers
  become: true
  tasks:
  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "label"
      - "node"
      - "{{ inventory_hostname }}"
      - "vice=true"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "label"
      - "node"
      - "{{ inventory_hostname }}"
      - "gpu=false"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "taint"
      - "node"
      - "{{ inventory_hostname }}"
      - "vice=only:NoSchedule"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

- name: Taint and Label the GPU Worker Nodes
  hosts: k8s_gpu_workers
  become: true
  tasks:
  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "label"
      - "node"
      - "vice=true"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "label"
      - "node"
      - "{{ inventory_hostname }}"
      - "gpu=true"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "taint"
      - "node"
      - "{{ inventory_hostname }}"
      - "vice=only:NoSchedule"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"

  - ansible.builtin.command:
      argv:
      - "kubectl"
      - "--kubeconfig"
      - "/etc/kubernetes/admin.conf"
      - "taint"
      - "node"
      - "{{ inventory_hostname }}"
      - "gpu=true:NoSchedule"
    delegate_to: "{{ groups['k8s_controllers'][0] }}"
