---
- name: prepare k3s nodes
  hosts: k3s_nodes
  become: true
  roles:
    - role: nodes

- name: set up first k3s control nodes
  hosts: k3s_controllers[0]
  become: true
  roles:
    - role: controllers

- name: set up remaining k3s control nodes
  hosts: k3s_controllers[1:]
  become: true
  roles:
    - role: controllers

- name: set up k3s DE worker nodes
  hosts: k3s_de_workers
  become: true
  roles:
    - role: service_workers

- name: set up k3s VICE worker nodes
  hosts: k3s_vice_workers
  become: true
  roles:
    - role: vice_workers

- name: set up k3s GPU worker nodes
  hosts: k3s_gpu_workers
  become: true
  roles:
    - role: gpu_workers
