---
- name: Install Docker
  hosts: k8s_nodes
  become: true
  roles:
  - role: cyverse.docker

- name: Install HAProxy
  hosts: k8s_api_proxy
  roles:
  - role: k8s_haproxy

- name: Open Ports
  hosts: k8s_nodes
  become: true
  tasks:
  - community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
    loop:
    - port: 6443
      proto: tcp
    - port: 2379:2380
      proto: tcp
    - port: 10250:10252
      proto: tcp
    - port: 6783:6784
      proto: tcp
    - port: 6783:6784
      proto: udp
    - port: 30000:32767
      proto: tcp

- name: Install Kubeadm
  hosts: k8s_nodes
  become: true
  roles:
  - role: kubeadm
