---
- name: Install HAProxy on VICE proxy
  hosts: outward-facing-proxy
  gather_facts: true
  become: yes
  roles:
    - { role: vice-haproxy-installer, include_dev: True }

  tasks:
    - name: reload haproxy
      systemd:
        daemon_reload: yes
        service: haproxy
        state: reloaded
        enabled: yes
