---
- delegate_to: localhost
  block:
    - name: create the grouper user
      community.postgresql.postgresql_user:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        db: "{{ pg_db }}"
        name: "{{ grouper_connection_user }}"
        password: "{{ grouper_connection_pass }}"
      when: create_user is defined and create_user and grouper is defined and grouper

    - name: create grouper database
      community.postgresql.postgresql_db:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        name: "{{ grouper_db_name }}"
        owner: "{{ grouper_connection_user }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"
      when: create_dbs is defined and create_dbs and grouper is defined and grouper
