---
- delegate_to: localhost
  block:
    - name: create the keycloak user
      community.postgresql.postgresql_user:
        login_host: "{{ groups['keycloak_dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        db: "{{ pg_db }}"
        name: "{{ keycloak_db_username }}"
        password: "{{ keycloak_db_password }}"
      when: create_user is defined and create_user

    - name: create the keycloak database
      community.postgresql.postgresql_db:
        login_host: "{{ groups['keycloak_dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        name: "{{ keycloak_db_name }}"
        owner: "{{ keycloak_db_username }}"
        encoding: "{{ encoding }}"
        lc_collate: "{{ lc_collate }}"
        lc_ctype: "{{ lc_ctype }}"
        template: "{{ template }}"
      when: create_dbs is defined and create_dbs
