---
- name: create unleash database
  delegate_to: localhost
  community.postgresql.postgresql_db:
    login_host: "{{ groups['dbms'][0] }}"
    port: "{{ pg_listen_port }}"
    login_user: "{{ pg_login_user }}"
    login_password: "{{ pg_login_password }}"
    name: "{{ unleash_db_name }}"
    owner: "{{ dbms_connection_user }}"
    encoding: "{{ encoding }}"
    lc_collate: "{{ lc_collate }}"
    lc_ctype: "{{ lc_ctype }}"
    template: "{{ template }}"
  when: create_dbs is defined and create_dbs and unleash is defined and unleash
