---

- name: add the pods and services sources to the trusted zone
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    zone: trusted
    state: enabled
    source: "{{ item }}"
  loop: "{{ k3s_zone_sources }}"
  notify: reload firewalld

- name: open the ports
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    port: "{{ item }}"
  loop:
    - "6443/tcp" # k3s api
    - "6444/tcp" # k3s api
    - "10250/tcp" # kubelet metrics
    - "5001/tcp" # embedded container image registry
    - "51280-51281/udp" # flannel wireguard
  notify: reload firewalld

