---
- name: create k3s zone
  ansible.posix.firewalld:
    zone: k3s
    state: present
    permanent: true
  register: k3s_zone_created

- name: reload firewalld service
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: k3s_zone_created.changed

- name: add the sources to the k3s zone
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    zone: k3s
    state: enabled
    source: "{{ item }}"
  loop: "{{ k3s_zone_sources }}"
  notify: reload firewalld

- name: open the ports
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    zone: k3s
    state: enabled
    port: "{{ item }}"
  loop:
    - "6443/tcp" # k3s api
    - "6444/tcp" # k3s api
    - "10250/tcp" # kubelet metrics
    - "5001/tcp" # embedded container image registry
    - "51280-51281/udp" # flannel wireguard
  notify: reload firewalld
