---
- name: add vice-cache deployment
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: cache-{{ image_name }}
      spec:
        selector:
          matchLabels:
            name: cache-{{ image_name }}
        template:
          metadata:
            labels:
              name: cache-{{ image_name }}
          spec:
            tolerations:
            - key: "vice"
              operator: "Equal"
              value: "only"
              effect: "NoSchedule"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: vice
                      operator: In
                      values:
                      - "true"
            containers:
            - name: cached-image-container
              image: "{{ image_name }}"
              command: ["true"]
