---
- name: set concourse path fact
  ansible.builtin.set_fact:
    concourse_bin: "{{ (concourse_install_dir, 'concourse/bin/concourse') | path_join }}"
  tags:
    - web
    - create_keys

- name: create_keys session signing key
  ansible.builtin.command:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./session_signing.key"
    create_keyss:
      - "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
  tags:
    - web
    - create_keys

- name: set session signing key permissions
  ansible.builtin.file:
    path: "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - web
    - create_keys

- name: create_keys the tsa host key
  cansible.builtin.ommand:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./tsa_host.key"
    create_keyss:
      - "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
  tags:
    - web
    - create_keys

- name: set session tsa host key permissions
  ansible.builtin.file:
    path: "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
    owner: "{{ concourse_user }/}"
    mode: '0644'
  tags:
    - web
    - create_keys

- name: concourse | set the path to the worker key file
  ansible.builtin.set_fact:
    concourse_worker_key: "{{(concourse_install_dir, 'worker.key') | path_join}}"
  tags:
    - web
    - create_keys

- name: create_keys the worker key
  ansible.builtin.command:
    cmd: "{{ concourse_bin }} generate-key -t rsa -f {{ concourse_worker_key }}"
    create_keyss:
      - "{{ concourse_worker_key }}"
  tags:
    - web
    - create_keys

- name: set worker key permissions
  ansible.builtin.file:
    path: "{{ concourse_worker_key }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - web
    - create_keys

- name: concourse | create_keys the authorized_worker_keys file
  ansible.builtin.copy:
    path: "{{(concourse_install_dir, 'authorized_worker_keys') | path_join }}"
    owner: "{{concourse_user}}"
    mode: '0644'
    content: "{{ lookup('ansible.builtin.file', concourse_worker_key) }}"
  tags:
    - web
    - create_keys

- name: download_keys session signing key
  ansible.builtin.fetch:
    flat: true
    src: "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
    dest: "./"
  tags:
    - web
    - download_keys

- name: download_keys tsa host key
  ansible.builtin.fetch:
    flat: true
    src: "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
    dest: "./"
  tags:
    - web
    - download_keys

- name: download_keys worker key
  ansible.builtin.fetch:
    flat: true
    src: "{{ (concourse_install_dir, 'worker.key') | path_join }}"
    dest: "./"
  tags:
    - web
    - download_keys

- name: upload_keys session signing key
  ansible.builtin.copy:
    src: "./session_signing.key"
    dest: "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - worker
    - upload_keys

- name: upload_keys tsa host key
  ansible.builtin.copy:
    src: "./tsa_host.key"
    dest: "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - worker
    - upload_keys

- name: upload_keys worker key
  ansible.builtin.copy:
    src: "./worker.key"
    dest: "{{ (concourse_install_dir, 'worker.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - worker
    - upload_keys
