---
- name: set concourse path fact
  ansible.builtin.set_fact:
    concourse_bin: "{{ (concourse_install_dir, 'concourse/bin/concourse') | path_join }}"
  tags:
    - keys
    - web
    - create

- name: create session signing key
  ansible.builtin.command:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./session_signing.key"
    creates:
      - "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
  tags:
    - keys
    - web
    - create

- name: set session signing key permissions
  ansible.builtin.file:
    path: "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - keys
    - web
    - create

- name: create the tsa host key
  cansible.builtin.ommand:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./tsa_host.key"
    creates:
      - "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
  tags:
    - keys
    - web
    - create

- name: set session tsa host key permissions
  ansible.builtin.file:
    path: "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - keys
    - web
    - create

- name: create the worker key
  ansible.builtin.command:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./worker.key"
    creates:
      - "{{ (concourse_install_dir, 'worker.key') | path_join }}"
  tags:
    - keys
    - web
    - create

- name: set worker key permissions
  ansible.builtin.file:
    path: "{{ (concourse_install_dir, 'worker.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - keys
    - web
    - create

- name: download session signing key
  ansible.builtin.fetch:
    flat: true
    src: "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
    dest: "./"
  tags:
    - keys
    - web
    - download

- name: download tsa host key
  ansible.builtin.fetch:
    flat: true
    src: "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
    dest: "./"
  tags:
    - keys
    - web
    - download

- name: download worker key
  ansible.builtin.fetch:
    flat: true
    src: "{{ (concourse_install_dir, 'worker.key') | path_join }}"
    dest: "./"
  tags:
    - keys
    - web
    - download

- name: upload session signing key
  ansible.builtin.copy:
    src: "./session_signing.key"
    dest: "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - keys
    - worker
    - upload

- name: upload tsa host key
  ansible.builtin.copy:
    src: "./tsa_host.key"
    dest: "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - keys
    - worker
    - upload

- name: upload worker key
  ansible.builtin.copy:
    src: "./worker.key"
    dest: "{{ (concourse_install_dir, 'worker.key') | path_join }}"
    owner: "{{ concourse_user }}"
    mode: '0644'
  tags:
    - keys
    - worker
    - upload
