---
- name: set concourse path fact
  set_fact:
    concourse_bin: "{{ (concourse_install_dir, 'concourse/bin/concourse') | path_join }}"

- name: create session signing key
  command:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./session_signing.key"
    creates:
      - "{{ (concourse_install_dir, 'session_signing.key') | path_join }}"

- name: create the tsa host key
  command:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./tsa_host.key"
    creates:
      - "{{ (concourse_install_dir, 'tsa_host.key') | path_join }}"

- name: create the worker key
  command:
    chdir: "{{ concourse_install_dir }}"
    cmd: "{{ concourse_bin }} generate-key -t rsa -f ./worker.key"
    creates:
      - "{{ (concourse_install_dir, 'worker.key') | path_join }}"

