---
- name: concourse | set the web environment file
  ansible.builtin.set_fact:
    concourse_env_file: "{{ (concourse_install_dir, 'env.conf') | path_join }}"
  tags:
    - web_systemd

- name: concourse | install web environment file
  ansible.builtin.copy:
    dest: "{{ concourse_env_file }}"
    mode: '0644'
    content: |
      CONCOURSE_ADD_LOCAL_USER={{concourse_login_user}}:{{concourse_login_password}}
      CONCOURSE_MAIN_TEAM_LOCAL_USER={{concourse_login_user}}
      CONCOURSE_SESSION_SIGNING_KEY={{(concourse_install_dir, 'session_signing.key') | path_join}}
      CONCOURSE_TSA_HOST_KEY={{(concourse_install_dir, 'tsa_host.key') | path_join}}
      CONCOURSE_TSA_AUTHORIZED_KEYS={{(concourse_install_dir, 'authorized_worker_keys') | path_join}}
      CONCOURSE_POSTGRES_HOST={{groups['dbms_primary'][0]}}
      CONCOURSE_POSTGRES_PORT={{pg_listen_port}}
      CONCOURSE_POSTGRES_DATABASE={{concourse_db}}
      CONCOURSE_POSTGRES_USER={{concourse_database_user}}
      CONCOURSE_POSTGRES_PASSWORD={{concourse_database_pass}}
  tags:
    - web_systemd

- name: concourse | install web systemd service file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/concourse-web.service"
    mode: '0644'
    content: |
      [Unit]
      Description=Concourse Web Service
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=1
      User={{concourse_user}}
      EnvironmentFile={{(concourse_install_dir, 'env.conf') | path_join}}
      ExecStart={{(concourse_install_dir, 'concourse/bin/concourse') | path_join}} web

      [Install]
      WantedBy=multi-user.target
  tags:
    - web_systemd

- name: concourse | set the worker directory
  ansible.builtin.set_fact:
    concourse_worker_dir: "{{(concourse_install_dir, 'worker') | path_join}}"
  tags:
    - worker_systemd

- name: concourse | create worker directory
  ansible.builtin.file:
    path: "{{ concourse_worker_dir }}"
    owner: "{{ concourse_user }}"
    state: directory
    mode: '0755'
  tags:
    - worker_systemd

- name: concourse | install worker environment file
  ansible.builtin.copy:
    dest: "{{ concourse_env_file }}"
    mode: '0644'
    content: |
      CONCOURSE_WORK_DIR={{concourse_worker_dir}}
      CONCOURSE_TSA_HOST={{groups['concourse_web'][0]:2222}}
      CONCOURSE_TSA_WORKER_PRIVATE_KEY={{(concourse_install_dir, 'worker.key') | path_join}}
  tags:
    - worker_systemd

- name: concourse | install worker service file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/concourse-worker.service"
    mode: '0644'
    content: |
      [Unit]
      Description=Concourse Worker Service
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=1
      User=root
      EnvironmentFile={{(concourse_install_dir, 'env.conf') | path_join}}
      ExecStart={{(concourse_install_dir, 'concourse/bin/concourse') | path_join}} worker

      [Install]
      WantedBy=multi-user.target
  tags:
    - worker_systemd

- name: concourse | enable and start concourse-web service
  ansible.builtin.service:
    name: concourse-web
    state: started
    enabled: true
  tags:
    - web_start

- name: concourse | enable and start concourse-worker service
  ansible.builtin.service:
    name: concourse-worker
    state: started
    enabled: true
  tags:
    - worker_start



