---
- name: Open the API Port
  become: true
  community.general.ufw:
    rule: allow
    port: 5443
    proto: tcp

- name: Install HAProxy
  become: true
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure HAProxy
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Restart HAProxy
  become: true
  ansible.builtin.systemd_service:
    name: haproxy
    enabled: true
    state: restarted
