---
_dbms_connection_user: "{{ dbms_connection_user | default('de') }}"
_dbms_connection_pass: "{{ dbms_connection_pass | default('Ch@ng3M3') }}"

k3s_token: "{{ k3s_token | default('K3sT0k3n') }}"

k3s_flannel_backend: "{{ k3s_flannel_backend | default('wireguard-native') }}"

k3s_registry_mirror: "{{ k3s_registry_mirror | default('https://registry-1.docker.io') }}"
k3s_registry_mirror_endpoint: "{{ k3s_registry_mirror_endpoint | default('https://registry-1.docker.io') }}"
k3s_registry_mirror_username: "{{ k3s_registry_mirror_username | default('') }}"
k3s_registry_mirror_password: "{{ k3s_registry_mirror_password | default('') }}"
k3s_registry_mirror_token: "{{ k3s_registry_mirror_token | default('') }}"
k3s_registry_mirror_ca_file: "{{ k3s_registry_mirror_ca_file | default('') }}"
k3s_registry_mirror_cert_file: "{{ k3s_registry_mirror_cert_file | default('') }}"
k3s_registry_mirror_key_file: "{{ k3s_registry_mirror_key_file | default('') }}"
k3s_registry_mirror_insecure_skip_verify: "{{ k3s_registry_mirror_insecure_skip_verify | default('false') }}"

k3s_datastore_endpoint: "{{ k3s_datastore_endpoint | default('') }}"

k3s_kubeconfig_output: "{{ k3s_kubeconfig_output | default('/etc/rancher/k3s/k3s.yaml') }}"
k3s_kubeconfig_mode: "{{ k3s_kubeconfig_mode | default('644') }}"
