---
- name: pull image-janitor image
  shell: docker pull harbor.cyverse.org/de/image-janitor:{{docker.tag}}

# TODO: come up with a way to generate the file and place it on the remote host
- name: ensure that jobservices.yml exists
  become: yes
  file:
    path: /etc/jobservices.yml
    state: touch

- name: install image-janitor
  shell: docker run --rm -v /usr/local/bin:/image-janitor --entrypoint "cp" harbor.cyverse.org/de/image-janitor:{{docker.tag}} /go/bin/image-janitor /image-janitor/image-janitor

- include: systemd.yml
