apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: default-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-cluster-issuer
spec:
  selfSigned: {}
