---
- ansible.builtin.import_tasks:
    file: de.yml
  tags:
    - de

- ansible.builtin.import_tasks:
    file: metadata.yml
  tags:
    - metadata

- ansible.builtin.import_tasks:
    file: notifications.yml
  tags:
    - notifications
# - ansible.builtin.import_tasks:
#     file: qms.yml
#   tags:
#     - qms
