---
- ansible.builtin.import_tasks:
    file: de.yml
  tags:
    - de

- ansible.builtin.import_tasks:
    file: fix_grouper.yml
  tags:
    - fix-grouper

- ansible.builtin.import_tasks:
    file: metadata.yml
  tags:
    - metadata

- ansible.builtin.import_tasks:
    file: notifications.yml
  tags:
    - notifications
