- name: install iptables
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - iptables
    - iptables-services
    - iptables-utils
  when: ansible_distribution_major_version == '7'
  tags: install

- name: stop and disable firewalld
  service: 
    name: firewalld 
    state: stopped 
    enabled: no
  when: ansible_distribution_major_version == '7'
  ignore_errors: true
  tags: disable-firewalld

- name: copy over firewall rules
  template: 
    src: "{{ item }}" 
    dest: "{{ FIREWALL_PATH }}" 
    mode: 0644 
    backup: yes
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.fw.j2"
    - "{{ ansible_distribution }}.fw.j2"
    - "{{ ansible_os_family }}.fw.j2"
    - "defaults.fw.j2"
  tags: copy-rules

- name: restart firewall (iptables)
  service: 
    name: "{{ FIREWALL_SERVICE }}" 
    state: restarted 
    enabled: yes
  tags: restart-iptables
