# tasks file to disable host firewall
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags: vars

# # handle centos-7 nonsense
# - include: CentOS-7.yml
#   when: ansible_distribution == "CentOS"  and ansible_distribution_major_version == '7'
#   tags: include-centos7

- name: install firewall
  action: >
      {{ ansible_pkg_mgr }} name={{ FIREWALL_SERVICE }} state=latest update_cache=yes
  tags: install

# Split out based on OS
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: ubuntu

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: centos
