- name: template applications
  template: 
    src: Ubuntu.app.j2 
    dest: "/etc/ufw/applications.d/{{ item.SCRIPT_NAME }}" 
    mode: 0644
  with_items: '{{ UFW_APPS_TEMPLATES }}'
  tags: ufw

- name: configure ufw rules
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: '{{ UFW_RULES }}'
  tags: copy-rules

- name: start ufw
  ufw:  
    state: enabled
  tags: start-ufw

- name: reload rules within ufw
  ufw: 
    state: reloaded
  tags: reload-ufw

# Help from: https://github.com/weareinteractive/ansible-ufw
