---
- name: build the release URL
  ansible.builtin.set_fact:
    release_url: "https://github.com/cyverse-de/road-runner/releases/download/{{road_runner_version}}"

- name: download the binary
  ansible.builtin.get_url:
    url: "{{release_url}}/road-runner"
    dest: "/usr/local/bin/road-runner"
    owner: "root"
    group: "root"
    mode: 0755
    force: true
