---
- name: Open the API Port
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ k8s_api_port }}" # k0s api
    - "9443" # join api
    - "8132" # konnectivity
  when: ansible_os_family == 'Debian'

- name: Open the API port
  become: true
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    zone: public
    state: enabled
    port: "{{ item }}"
  notify: reload firewalld
  with_items:
    - "{{ k8s_api_port }}/tcp" # k0s api port
    - "9443/tcp" # join api port
    - "8132/tcp" # konnectivity server
  when: ansible_os_family == 'RedHat'

- name: Install HAProxy
  become: true
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure HAProxy
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Restart HAProxy
  become: true
  ansible.builtin.systemd_service:
    name: haproxy
    enabled: true
    state: restarted
