---
- name: Open the API Port
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ k8s_api_port }}" # k0s api
    - "9443" # join api
    - "8132" # konnectivity
  when: ansible_os_family == 'Debian'

- name: Open the API port
  become: true
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    zone: public
    state: enabled
    port: "{{ item }}"
  notify: reload firewalld
  with_items:
    - "{{ k8s_api_port }}/tcp" # k0s api port
    - "9443/tcp" # join api port
    - "8132/tcp" # konnectivity server
  when: ansible_os_family == 'RedHat'

# - name: configure k8s haproxy settings
#   become: true
#   ansible.builtin.template:
#     src: 00_k8s.cfg.j2
#     dest: /etc/haproxy/conf.d/00_k8s.cfg.j2
#     owner: root
#     group: root
#     mode: 0644
#   notify:
#     - restart haproxy

- name: configure k8s haproxy settings
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    append_newline: true
    prepend_newline: true
    marker: "# {mark} K8S HAProxy Settings"
    block: "{{ lookup('template', '00_k8s.cfg.j2') }}"
  notify: restart haproxy
