---
- name: install longhorn
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: add the longhorn helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present

    - name: create the longhorn-system namespace
      kubernetes.core.k8s:
        name: longhorn-system
        state: present
        kind: namespace
        api_version: v1

    - name: install the longhorn helm chart
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        namespace: longhorn-system
        wait: true
        values:
          global:
            tolerations:
              - key: "vice"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
              - key: "analysis"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
          longhornManager:
            tolerations:
              - key: "vice"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
              - key: "analysis"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
          longhornUI:
            tolerations:
              - key: "vice"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
              - key: "analysis"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
          longhornDriver:
            tolerations:
              - key: "vice"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
              - key: "analysis"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
