---
- name: Add repo file
  get_url:
    dest: "/etc/yum.repos.d/docker-ce.repo"
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    mode: 0644
  tags:
    - install

- name: Install the docker compose plugin
  package:
    name: docker-compose-plugin
    state: present
  tags:
    - install
