---
- name: install role dependencies
  apt:
    pkg:
    - curl
    - gnupg
    - apt-transport-https
  become: true

- name: grab com.rabbitmq.team.gpg
  shell: curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/com.rabbitmq.team.gpg

- name: grab rabbitmq.E495BB49CC4BBE5B.gpg
  shell: curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg

- name: grab rabbitmq.9F4587F226208342.gpg
  shell: curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg

- name: create /etc/apt/sources.list.d/rabbitmq.list
  copy:
    src: rabbitmq.list
    dest: /etc/apt/sources.list.d/rabbitmq.list
    mode: 0644
    owner: root
    group: root
  become: true

- name: install rabbitmq-server
  apt:
    pkg:
    - erlang-base
    - erlang-asn1 
    - erlang-crypto 
    - erlang-eldap 
    - erlang-ftp 
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon 
    - erlang-parsetools 
    - erlang-public-key
    - erlang-runtime-tools 
    - erlang-snmp 
    - erlang-ssl
    - erlang-syntax-tools 
    - erlang-tftp 
    - erlang-tools 
    - erlang-xmerl
    - rabbitmq-server
  become: true

- name: start RabbitMQ
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: true

- name: list explicitly enabled RabbitMQ plugins matching `rabbitmq_management`
  command:
    argv:
      - rabbitmq-plugins
      - list
      - -E
      - rabbitmq_management
  register: mgmt_plugin_listing
  changed_when: false
  become: true

- name: enable the RabbitMQ management plugin
  block:
    - command:
        argv:
          - rabbitmq-plugins
          - enable
          - rabbitmq_management
    - systemd:
        name: rabbitmq-server
        state: restarted
        enabled: yes
  when: not mgmt_plugin_listing is search("\srabbitmq_management\s")
  become: true

- name: create the admin user
  rabbitmq_user:
    user: "{{ admin_user }}"
    password: "{{ admin_password }}"
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    tags: administrator
  become: true

- name: remove the guest user
  when: admin_user != "guest"
  rabbitmq_user:
    user: guest
    state: absent
  become: true
