apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openebs-ndm
  namespace: openebs
spec:
  template:
    spec:
      tolerations:
        - key: "vice"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
        - key: "analysis"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-ndm-operator
  namespace: openebs
spec:
  template:
    spec:
      tolerations:
        - key: "vice"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
        - key: "analysis"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-ndm-cluster-exporter
  namespace: openebs
spec:
  template:
    spec:
      tolerations:
        - key: "vice"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
        - key: "analysis"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openebs-ndm-node-exporter
  namespace: openebs
spec:
  template:
    spec:
      tolerations:
        - key: "vice"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
        - key: "analysis"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-localpv-provisioner
  namespace: openebs
spec:
  template:
    spec:
      tolerations:
        - key: "vice"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
        - key: "analysis"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
