---
- include: prereqs.yml

- name: "Encode the Root Password"
  become: true
  command:
  args:
    argv:
      - "slappasswd"
      - "-s"
      - "{{ root_password }}"
  register: slappasswd

- name: "Generate the OpenLDAP Configuration File"
  become: true
  template:
    src: "slapd.conf.j2"
    dest: "/etc/ldap/ldap.conf"
    owner: root
    mode: 0644

- name: "Start the OpenLDAP Server"
  become: true
  systemd:
    name: slapd
    daemon_reload: true
    enabled: true
    state: restarted

- include: entities.yml
