---
- name: "Install OpenLDAP Clients"
  become: true
  package:
    name: ldap-utils
    state: present

- name: "Install OpenLDAP Server"
  become: true
  package:
    name: slapd
    state: present

- name: "Install python-ldap"
  become: true
  package:
    name: "python{{ ansible_python_version.split('.')[0] }}-ldap"
    state: present
