---
- name: install concourse
  hosts: concourse
  roles:
    - role: concourse_install

- name: create keys
  hosts: concourse_web[0]
  roles:
    - role: concourse_keys_create

- name: upload keys
  hosts: concourse_worker,concourse_web[1:]
  roles:
    - role: concourse_keys_upload

- name: web systemd
  hosts: concourse_web
  roles:
    - role: concourse_systemd_web

- name: worker systemd
  hosts: concourse_worker
  roles:
    - role: concourse_systemd_worker

- name: start web service
  hosts: concourse_web
  become: true
  tasks:
    - name: concourse | enable and start concourse-web service
      ansible.builtin.service:
        name: concourse-web
        state: started
        enabled: true

- name: start worker service
  hosts: concourse_worker
  become: true
  tasks:
    - name: concourse | enable and start concourse-worker service
      ansible.builtin.service:
        name: concourse-worker
        state: started
        enabled: true

