---
- name: install prerequisites
  hosts: condor
  become: true
  tasks:
  - package:
      name: "python3-pip"
      state: "present"
  - package:
      name: curl
      state: present
  - pip:
      name: "docker"
      state: present

- name: set the time zone
  hosts: condor
  become: true
  roles:
  - role: timezone

- name: install docker
  hosts: condor_worker
  become: true
  roles:
  - role: cyverse-ansible.docker

- name: download condor install script
  become: true
  hosts: condor
  tasks:
    - ansible.builtin.get_url:
        url: https://get.htcondor.org
        dest: /root/condor_install.sh
        mode: '0755'

- name: install the central manager
  become: true
  hosts: condor_manager
  tasks:
    - ansible.builtin.shell:
        cmd: ./condor_install.sh --no-dry-run --password "{{ condor_pool_password }}" --central-manager "{{ groups['condor_manager'][0] }}"
        chdir: '/root/'
        creates: '/usr/sbin/condor_master'

- name: install the submit node
  become: true
  hosts: condor_submit
  tasks:
    - ansible.builtin.shell:
        cmd: ./condor_install.sh --no-dry-run --password "{{ condor_pool_password }}" --submit "{{ groups['condor_manager'][0] }}"
        chdir: '/root/'
        creates: '/usr/sbin/condor_master'
  roles:
    - condor_launcher
    - de-road-runner

- name: install the worker nodes
  become: true
  hosts: condor_worker
  tasks:
    - ansible.builtin.shell:
        cmd: ./condor_install.sh --no-dry-run --password "{{ condor_pool_password }}" --submit "{{ groups['condor_manager'][0] }}"
        chdir: '/root/'
        creates: '/usr/sbin/condor_master'
  roles:
    - de-docker-logging-plugin
    - de-image-janitor
    - de-network-pruner
    - condor-worker-docker-registries

