---
- hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  tasks:
    - ansible.builtin.include_role:
        name: services
        tasks_from: main
      vars:
        project_name: "{{ project }}"
      tags:
        - deploy
