---
- name: set the k3s yaml file
  become: true
  hosts: k3s_controllers[0]
  roles:
    - role: gocd_agent_kubeconfig

- name: transfer the k3s yaml file
  become: true
  hosts: gocd_agent
  roles:
    - role: gocd_kubeconfig_xfer
