---
- name: install gocd-server
  become: true
  hosts: gocd_server
  pre_tasks:
    - name: gather facts about the de_proxy nodes
      setup:
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{groups['de_proxy']}}"
  roles:
    - role: gocd_server

- name: install gocd-agent
  become: true
  hosts: gocd_agent
  pre_tasks:
    - name: gather facts about the de_proxy nodes
      setup:
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{groups['de_proxy']}}"
  roles:
    - role: gocd_agent

