---
- name: set the k3s yaml file
  hosts: k8s_controllers[0]
  connection: local
  become: false
  roles:
    - role: gocd_agent_kubeconfig

- name: transfer the k3s yaml file
  become: true
  hosts: gocd_agent
  roles:
    - role: gocd_kubeconfig_xfer
