---
- name: install postgresql
  ansible.builtin.import_playbook: postgresql.yml

- name: set up databases
  ansible.builtin.import_playbook: postgresql_init.yml

- name: set up k3s haproxy
  ansible.builtin.import_playbook: kubernetes_setup_haproxy.yml

- name: install k3s
  ansible.builtin.import_playbook: kubernetes.yml

- name: install DE requirements into k3s
  ansible.builtin.import_playbook: kubernetes_de_reqs.yml

- name: install irods-csi-driver into k3s
  ansible.builtin.import_playbook: kubernetes_install_csi_driver.yml

- name: install cert-manager into k3s
  ansible.builtin.import_playbook: cert_manager.yml

- name: install nats into k3s
  ansible.builtin.import_playbook: nats.yml

- name: install grouper into k3s
  ansible.builtin.import_playbook: grouper.yml

- name: install keycloak into k3s
  ansible.builtin.import_playbook: keycloak.yml

- name: install harbor into k3s
  ansible.builtin.import_playbook: harbor.yml
