---
# This is limited to the first controller node to prevent it from
# running multiple times, once per host. It's not actually limited
# to the first controller node.
- name: Install the DE requirements into the cluster
  hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  roles:
    - role: k8s_de_reqs

- name: set up ingresses
  hosts: k8s_controllers[0]
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: kubernetes_ingresses

- name: set up networking related options in k3s
  hosts: k8s_controllers[0]
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: kubernetes_networking
