---
- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
    - role: postgresql
    - role: postgresql_access

- name: initialize dbs
  hosts: dbms
  become: false
  connection: local
  roles:
    - role: postgresql_init
