---
- hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  tags:
    - configure-services
  roles:
    - role: service_configurations

- hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  tags:
    - deploy-single-service
  tasks:
    - ansible.builtin.include_role:
        name: services
        tasks_from: main
      vars:
        project_name: "{{ project }}"
      tags:
        - deploy
      when: "'deploy-single-service' in ansible_run_tags"

- hosts: k8s_controllers[0]
  connection: local
  gather_facts: false
  tags:
    - deploy-all-services
  tasks:
    - ansible.builtin.include_role:
        name: services
        tasks_from: main
      vars:
        project_name: "{{ item }}"
      tags:
        - deploy
      with_items:
        - analyses
        - app-exposer
        - apply-labels
        - apps
        - async-tasks
        - bulk-typer
        - check-resource-access
        - clockwork
        - data-info
        - de-mailer
        - de-webhooks
        - dewey
        - discoenv-analyses
        - discoenv-users
        - email-requests
        - event-recorder
        - get-analysis-id
        - info-typer
        - infosquito2
        - iplant-groups
        - jex-adapter
        - job-status-listener
        - job-status-recorder
        - job-status-to-apps-adapter
        - kifshare
        - metadata
        - notifications
        - permissions
        - qms
        - qms-adapter
        - requests
        - resource-usage-api
        - data-usage-api
        - subscriptions
        - timelord
        - user-info
        - vice-default-backend
        - vice-status-listener
        - search
        - dashboard-aggregator
        - terrain
        - sonora
