### Deploys a single service specified by the `service` extra var.
---
- hosts: k3s_controllers[0]
  gather_facts: false
  tasks:
    - name: deploy services
      block:
        - ansible.builtin.include_role: 
            name: services
          vars:
            project_name: "{{ service }}"
      delegate_to: localhost
      tags:
        - deploy
