---
- hosts: k3s_controllers[0]
  gather_facts: false
  roles:
    - role: service_configurations
      tags:
        - configs
  tasks:
    - name: deploy services
      block:
        - name: list of build files
          ansible.builtin.find:
            paths: "{{ de_releases_dir}}/builds"
            patterns: "*.json"
            file_type: file
          register: build_json_files

        - name: list of project names
          ansible.builtin.set_fact:
            project_names: "{{ project_names|default([]) + [item.path|basename|splitext|first] }}"
          loop: "{{ build_json_files.files }}"

        - name: filter project names
          ansible.builtin.set_fact:
            project_names: "{{ project_names | intersect(projects)}}"
          when: projects is defined

        - ansible.builtin.debug:
            msg: "{{ projects }}"
          when: projects is defined

        - ansible.builtin.debug:
            msg: "{{ project_names }}"

        - ansible.builtin.include_role: 
            name: services
          vars:
            project_name: "{{ item }}"
          loop: "{{ project_names }}"
      delegate_to: localhost
      tags:
        - deploy

