---
- name: remove the condor package
  hosts: condor
  become: true
  tasks:
    - ansible.builtin.service:
        name: condor
        state: stopped
        enabled: false
    - ansible.builtin.package:
        name: condor
        state: absent
    - ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/condor
        - /var/lib/condor
        - /root/condor_install.sh
        - /root/condor_config.local
