---
- name: Create the logging directory
  ansible.builtin.file:
    path: /var/log/de-docker-logging-plugin
    state: directory

- name: get the information about the condor user
  ansible.builtin.getent:
    database: passwd
    key: condor

- name: install the plugin
  community.docker.docker_plugin:
    alias: de-logging
    plugin_name: discoenv/de-docker-logging-plugin:{{de_docker_logging_plugin_tag}}
    state: present

- name: disable the plugin
  community.docker.docker_plugin:
    alias: de-logging
    plugin_name: discoenv/de-docker-logging-plugin:{{de_docker_logging_plugin_tag}}
    state: disable

- name: reconfigure and enable the plugin
  community.docker.docker_plugin:
    alias: de-logging
    plugin_name: discoenv/de-docker-logging-plugin:{{de_docker_logging_plugin_tag}}
    plugin_options:
      de-log-directory.source: /var/lib/condor
      uid: "{{ ansible_facts.getent_passwd['condor'][1] }}"
      gid: "{{ ansible_facts.getent_passwd['condor'][2] }}"
    state: enable
