---
- ansible.builtin.stat: path=/usr/local/bin/k3s
  register: k3s_installed_c0

- name: install k3s
  environment:
    INSTALL_K3S_EXEC: "server"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_TOKEN: "{{ k3s_token }}"
    K3S_DATASTORE_ENDPOINT: "{{ k3s_datastore_endpoint }}"
    K3S_KUBECONFIG_OUTPUT: "{{ k3s_kubeconfig_output }}"
    K3S_KUBECONFIG_MODE: "{{ k3s_kubeconfig_mode }}"
  ansible.builtin.shell: /tmp/k3s_install.sh --flannel-backend "{{ k3s_flannel_backend }}" --tls-san "{{ groups['k3s_api_proxy'][0] }}" --embedded-registry
  when: not k3s_installed_c0.stat.exists or force_reinstall | bool

- name: start k3s service
  ansible.builtin.service:
    name: k3s
    state: restarted
    enabled: true
