---
- name: k3s db init | create connection user
  community.postgresql.postgresql_user:
    login_host: "{{ pg_login_host }}"
    port: "{{ pg_listen_port }}"
    login_user: "{{ pg_login_user }}"
    login_password: "{{ pg_login_password }}"
    db: "{{ pg_db }}"
    name: "{{ _dbms_connection_user }}"
    password: "{{ _dbms_connection_pass }}"

- name: k3s db init | create database
  community.postgresql.postgresql_db:
    login_host: "{{ pg_login_host }}"
    port: "{{ pg_listen_port }}"
    login_user: "{{ pg_login_user }}"
    login_password: "{{ pg_login_password }}"
    name: "k3s"
    owner: "{{ _dbms_connection_user }}"
    encoding: "{{ encoding }}"
    lc_collate: "{{ lc_collate }}"
    lc_ctype: "{{ lc_ctype }}"
    template: "{{ template }}"
    state: present
