---

- name: install | apt install postgresql and postgresql client
  apt:
    update_cache: true
    pkg:
      - "postgresql-{{_dbms_postgresql_version}}"
      - "postgresql-client-{{_dbms_postgresql_version}}"
      - "python3-psycopg2"
    state: present

- name: install | create en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present
