---
- name: databases | create connection user
  community.postgresql.postgresql_user:
    db: "{{ pg_db }}"
    port: "{{ pg_listen_port }}"
    name: "{{ _dbms_connection_user }}"
    password: "{{ _dbms_connection_pass }}"
  become: true
  become_user: postgres

- name: databases | create de database
  community.postgresql.postgresql_db:
    name: "de"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: databases | create notifications database
  community.postgresql.postgresql_db:
    name: "notifications"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: databases | create permissions database
  community.postgresql.postgresql_db:
    name: "permissions"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: databases | create metadata database
  community.postgresql.postgresql_db:
    name: "metadata"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: databases | create grouper database
  community.postgresql.postgresql_db:
    name: "grouper"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: databases | create qms database
  community.postgresql.postgresql_db:
    name: "qms"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: databases | create unleash database
  community.postgresql.postgresql_db:
    name: "unleash"
    port: "{{ pg_listen_port }}"
    owner: "{{ _dbms_connection_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres
