apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: dbuser
  behavior: merge
  literals:
  - username=db_user
  - password=super-secret-password
- name: kcadmin
  behavior: merge
  literals:
  - username=aws_admin
  - password=even-more-secret-password
configMapGenerator:
- name: keycloak-config
  behavior: merge
  literals:
  - KEYCLOAK_HOSTNAME=auth.example.org
  - DB_VENDOR=postgres
  - DB_ADDR=db.example.org
  - DB_PORT=5432
bases:
- ../../base
patchesStrategicMerge:
- node-port-service.yaml
