---
- name: install the nvidia container repo if not present
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
    dest: /etc/yum.repos.d/nvidia-container-toolkit.repo
    mode: 0644

- name: install the container toolkit packages
  ansible.builtin.package:
    name:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
      - libnvidia-container-tools
      - libnvidia-container1
    state: present
  notify: reboot host

- name: configure the nvidia container toolkit runtime
  ansible.builtin.command:
    argv:
      - nvidia-ctk
      - runtime
      - configure
      - --set-as-default
      - --config
      - "{{ nvidia_container_toolkit_runtime_config_path }}"
      - --runtime
      - "{{ nvidia_container_toolkit_runtime }}"
    creates: "{{ nvidia_container_toolkit_runtime_config_path }}"
  notify: reboot host
