---

- name: install condor when centos
  block:
    - name: import the PGP key used by HTCondor
      rpm_key:
        key: "https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key"
        state: "present"

    - name: add the YUM repository file
      yum:
        name: "https://research.cs.wisc.edu/htcondor/repo/current/htcondor-release-current.el8.noarch.rpm"
        state: "present"

    - name: install Condor
      yum:
        name: "condor-all"
        state: "present"
        enablerepo: "powertools"
  when: ansible_facts['distribution'] == 'CentOS'

- name: install condor when ubuntu
  block:
    - name: get the apt key
      ansible.builtin.get_url:
        url: https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key
        dest: /etc/apt/keyrings/HTCondor-10.x-Key

    - name: copy /etc/apt/sources.list.d/htcondor.sources
      template:
        src: htcondor.sources.j2
        dest: /etc/apt/sources.list.d/htcondor.sources

    - name: install htcondor
      apt:
        pkg:
          - htcondor
        state: present
        update_cache: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true

- name: ensure that the execute directory exists
  file:
    path: "{{ condor_exec_dir }}"
    state: "directory"
    owner: "condor"
    group: "condor"
    mode: 0755

- name: generate the main configuration file
  template:
    src: "condor_config.local"
    dest: "/etc/condor/condor_config.local"
    owner: "root"
    group: "root"
    mode: 0644

- name: generate the execution directory configuration file
  template:
    src: "exec-dir"
    dest: "/etc/condor/config.d/exec-dir"
    owner: "root"
    group: "root"
    mode: 0644

- name: store the pool password
  command: "condor_store_cred -f /var/lib/condor/pool_password -p {{ condor_password | quote }}"
  when: condor_password != ""
