---
- name: check for comment in /etc/sysconfig/iptables
  command: "grep -Fxq '# Kubernetes' /etc/sysconfig/iptables"
  register: check_for_comment
  check_mode: no
  failed_when: check_for_comment.rc == 2
  changed_when: check_for_comment.rc == 0
  ignore_errors: yes
  tags:
    - firewall

- name: add firewall rules
  when: check_for_comment.changed
  blockinfile:
    insertafter: "# Kubernetes"
    marker: "## {mark} Kubernetes"
    path: /etc/sysconfig/iptables
    block: |
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 10250 -j ACCEPT -m comment --comment "kubelet api access"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 30000:32767 -j ACCEPT -m comment --comment "node ports"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 6783 -j ACCEPT -m comment --comment "weavenet tcp"
      -A INPUT -m state --state NEW -m udp -p udp --dport 6783:6784 -j ACCEPT -m comment --comment "weavenet udp"
  tags:
    - firewall
